### ISSUE TITLE
RimRadio creates "Human_Meat" etc. errors, and kills music

### ISSUE THREAD

**Issue by MitztheKat** [alextd/RimWorld-ReplaceStuff#3]
i created 3 logs and one is a duplicate.
https://git.io/fbp2A
[output_log (1).txt](https://github.com/alextd/RimWorld-ReplaceStuff/files/2167081/output_log.1.txt)
music mods do not work with this mod. ??

**Comment by alextd** [comment]
There are a few dozen mods enabled on this log

No reason to thing it's Replace Stuff

**Comment by MitztheKat** [comment]
i have tested with and without extra mods.

**Comment by MitztheKat** [comment]
i will get better logs if you ask for it.

**Comment by MitztheKat** [comment]
hey, i'd like to bump this saying it's still broken. i added in the RimRadio mod and it breaks with lots of hoomin meat problems.

**Comment by alextd** [comment]
Yea RimRadio is the cause here, and has an error by itself:

Loader exceptions:
   => System.TypeLoadException: Could not load type 'Newtonsoft.Json.Utilities.EnumUtils+<>c' from assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

ReplaceStuff also loads types so hits the same error

Mentioned it on RimRadio: https://steamcommunity.com/sharedfiles/filedetails/?id=1426346991
